/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OffresRouteImport } from './routes/offres'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardArchitecteRouteImport } from './routes/dashboard-architecte'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ArchitectesRouteImport } from './routes/architectes'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectIdRouteImport } from './routes/architect.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresRoute = OffresRouteImport.update({
  id: '/offres',
  path: '/offres',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardArchitecteRoute = DashboardArchitecteRouteImport.update({
  id: '/dashboard-architecte',
  path: '/dashboard-architecte',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectesRoute = ArchitectesRouteImport.update({
  id: '/architectes',
  path: '/architectes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectIdRoute = ArchitectIdRouteImport.update({
  id: '/architect/$id',
  path: '/architect/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architectes': typeof ArchitectesRoute
  '/booking': typeof BookingRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-architecte': typeof DashboardArchitecteRoute
  '/login': typeof LoginRoute
  '/offres': typeof OffresRoute
  '/search': typeof SearchRoute
  '/architect/$id': typeof ArchitectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architectes': typeof ArchitectesRoute
  '/booking': typeof BookingRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-architecte': typeof DashboardArchitecteRoute
  '/login': typeof LoginRoute
  '/offres': typeof OffresRoute
  '/search': typeof SearchRoute
  '/architect/$id': typeof ArchitectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architectes': typeof ArchitectesRoute
  '/booking': typeof BookingRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-architecte': typeof DashboardArchitecteRoute
  '/login': typeof LoginRoute
  '/offres': typeof OffresRoute
  '/search': typeof SearchRoute
  '/architect/$id': typeof ArchitectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/architectes'
    | '/booking'
    | '/comment-ca-marche'
    | '/dashboard'
    | '/dashboard-architecte'
    | '/login'
    | '/offres'
    | '/search'
    | '/architect/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/architectes'
    | '/booking'
    | '/comment-ca-marche'
    | '/dashboard'
    | '/dashboard-architecte'
    | '/login'
    | '/offres'
    | '/search'
    | '/architect/$id'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/architectes'
    | '/booking'
    | '/comment-ca-marche'
    | '/dashboard'
    | '/dashboard-architecte'
    | '/login'
    | '/offres'
    | '/search'
    | '/architect/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ArchitectesRoute: typeof ArchitectesRoute
  BookingRoute: typeof BookingRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  DashboardRoute: typeof DashboardRoute
  DashboardArchitecteRoute: typeof DashboardArchitecteRoute
  LoginRoute: typeof LoginRoute
  OffresRoute: typeof OffresRoute
  SearchRoute: typeof SearchRoute
  ArchitectIdRoute: typeof ArchitectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres': {
      id: '/offres'
      path: '/offres'
      fullPath: '/offres'
      preLoaderRoute: typeof OffresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-architecte': {
      id: '/dashboard-architecte'
      path: '/dashboard-architecte'
      fullPath: '/dashboard-architecte'
      preLoaderRoute: typeof DashboardArchitecteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architectes': {
      id: '/architectes'
      path: '/architectes'
      fullPath: '/architectes'
      preLoaderRoute: typeof ArchitectesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architect/$id': {
      id: '/architect/$id'
      path: '/architect/$id'
      fullPath: '/architect/$id'
      preLoaderRoute: typeof ArchitectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ArchitectesRoute: ArchitectesRoute,
  BookingRoute: BookingRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  DashboardRoute: DashboardRoute,
  DashboardArchitecteRoute: DashboardArchitecteRoute,
  LoginRoute: LoginRoute,
  OffresRoute: OffresRoute,
  SearchRoute: SearchRoute,
  ArchitectIdRoute: ArchitectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
